### ISSUE TITLE
I want auto close private channel

### ISSUE THREAD

**Issue by mikkame** [Symantec/slack-autoarchive#24]
Hi.

I try replace 'channels' to 'groups' in the code.

It is good worked.

**Comment by JohnTheodore** [comment]
I don't believe the api key has access to introspect all private channels? You could probably introspect say the private channels your user is in. I'm not sure if it's possible to introspect private channels you aren't a member of.

**Comment by mikkame** [comment]
@JohnTheodore 
Hi!.
Thanks for your response.

Surely you are right.
