### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by pvmhay** [Symantec/slack-autoarchive#28]
Receving this error when trying to run. The dry run works perfectly. This only happens when the Dry Run is set to False.

C:\Python36\slack-autoarchive-master>python slack-autoarchive.py
..Archiving channel... agile
Traceback (most recent call last):
  File "slack-autoarchive.py", line 198, in <module>
    channel_reaper.main()
  File "slack-autoarchive.py", line 191, in main
    self.archive_channel(channel, alert_templates['channel_template'])
  File "slack-autoarchive.py", line 162, in archive_channel
    channel_message = alert % self.days_inactive
TypeError: not enough arguments for format string

**Comment by kellyebler** [comment]
@pvmhay I was able to fix this by changing line 162 in the script to:
`channel_message = alert.format(self.days_inactive)`
Happy to submit a PR for this!

Edit: This would actually be my first bug fix on GitHub, so I'd love to take this one.

**Comment by pvmhay** [comment]
@keeblers-n-bits You rock, that worked perfectly! Thank you!
