### ISSUE TITLE
Wondering if this is going to be updated so as to use "Slack apps" instead of legacy tokens

### ISSUE THREAD

**Issue by sethgoldin** [Symantec/slack-autoarchive#31]
Just ran this OK, and it works great! Thank you!

I'm just wondering if this might be updated so as to use "Slack apps" in the future. When I went to go create a token, I got [a warning that tokens were EOL](https://api.slack.com/custom-integrations/legacy-tokens), and could stop working at any time. When Slack does pull the plug on the legacy tokens, I'd love to continue to be able to use this script, or some modified form of it.

**Comment by JohnTheodore** [comment]
sounds reasonable. send a PR if you want.

**Comment by sethgoldin** [comment]
This is beyond my skill set for now, so probably won't be able to get to it for several weeks or months. Might be better suited for someone on the project more familiar with the Slack API.

**Comment by sethgoldin** [comment]
Turn out this was a bit easier than I thought it would be.

Nothing in the Python code actually needs to be changed. It's just `README.md` that should be updated so as to reflect what permission scopes the particular Slack app needs.

When using the OAuth token, the script just kept spitting out errors. The script doesn't really return any error message from Slack, but I just went through `slack-autoarchive.py` looking at all the `api_endpoints`. Then I looked through [Slack's documentation for the particular API methods](https://api.slack.com/methods). Turns out that for the particular Slack app, you can look up particular methods right in the search bar for the permission scopes. Some of the script's methods overlap for the particular permission scopes that they need. Anyway, I have a complete list now:

- `channels:history`
- `channels:read`
- `channels:write`
- `chat:write:bot`
- `chat:write:user`

Easy enough once you add those permission scopes. I'll update `README.md` and send a pull request. Thanks.

**Comment by JohnTheodore** [comment]
great, sounds like a reasonable PR. After you send it, I'll close this issue.

**Comment by sethgoldin** [comment]
#32 should be all we need here.

**Comment by JohnTheodore** [comment]
Thanks for the PR!
