### ISSUE TITLE
How can we archive channels which are inactive from last 180 days.

### ISSUE THREAD

**Issue by hi-Das** [Symantec/slack-autoarchive#40]
I understand this code archives channels which Has non-bot messages in the past 60 days. So how can we change it to 180 days ? I looked through the code but couldn't find the line. 

Thanks.

**Comment by dsmetham** [comment]
This setting is defined in the config.py file

days_inactive = int(os.environ.get('DAYS_INACTIVE', 60))

**Comment by dsmetham** [comment]
This setting is in the config.py file

days_inactive = int(os.environ.get('DAYS_INACTIVE', 60))

**Comment by hi-Das** [comment]
Yep. found it yesterday. Thank you @dsmetham .
