### ISSUE TITLE
Scopes organization has changed

### ISSUE THREAD

**Issue by sethgoldin** [Symantec/slack-autoarchive#44]
Running into an issue with:
```TypeError: 'NoneType' object is not subscriptable```

I went back to check the scopes on the token, and I'm seeing that `channels:write` doesn't exist anymore. Trying to figure out what scopes are actually required now.

**Comment by sethgoldin** [comment]
Oops, the issue was with IP addresses. However, the scopes are organized differently now. These should be updated.

**Comment by sethgoldin** [comment]
Not sure if this is related to the permissions scopes, but no message from the "Channel Reaper" showed up when I archived a handful of channels.

**Comment by aharpervc** [comment]
What are the replacement scopes you used?

**Comment by sethgoldin** [comment]
> What are the replacement scopes you used?

I changed the documentation for the correct scopes here: https://github.com/Symantec/slack-autoarchive/pull/32

**Comment by aharpervc** [comment]
Hm, that mentions `channels:write`, but isn't that one of the old scopes?

**Comment by sethgoldin** [comment]
@aharpervc I don't know. I haven't run this script in a while. This code seems to refer to the deprecated legacy tokens. Nothing I input as a `SLACK_TOKEN` seems to work now. I've tried each of the following:
- Signing secret
- Verification token
- OAuth Access Token
- Bot User OAuth Access Token

None of those work, though.

@JohnTheodore Is there any chance of this code being updated to use the proper [oauth.v2.access](https://api.slack.com/methods/oauth.v2.access) app credentials?

**Comment by JohnTheodore** [comment]
I left the company awhile ago. This github project is not maintained by anyone sadly. I'd just go with which ever fork has the most new activity?

**Comment by sethgoldin** [comment]
Looks like this fork is the one that works now: https://github.com/grailbio-external/slack-autoarchive

https://github.com/Symantec/slack-autoarchive is dead! Long live https://github.com/grailbio-external/slack-autoarchive!
