### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by dougr-code** [Symantec/slack-autoarchive#46]
First off, thank you so much for this, awesome idea. I'm encountering the issue below as was hoping you had an idea for a fix.

SLACK_TOKEN=xxxxxxx python slack_autoarchive.py
2020-06-18 13:12:27,331 - INFO - THIS IS A DRY RUN. NO CHANNELS ARE ACTUALLY ARCHIVED.
Traceback (most recent call last):
  File "slack_autoarchive.py", line 253, in <module>
    CHANNEL_REAPER.main()
  File "slack_autoarchive.py", line 235, in main
    for channel in self.get_all_channels():
  File "slack_autoarchive.py", line 108, in get_all_channels
    payload=payload)['channels']
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by alexeiser** [comment]
Until https://github.com/Symantec/slack-autoarchive/pull/45 gets merged. You can use my fork which is updated to the new slack tokens required if you created the slack project in the last 2 weeks.

**Comment by dougr-code** [comment]
Fantastic! Thank you! Using your fork worked.

Now I just need to figure out why it only pulls 8 channels out of hundreds even when I set days inactive and min participants both to 0.

**Comment by dougr-code** [comment]
Thank you, alexeiser.

**Comment by alexeiser** [comment]
Probably because of paging... 
https://github.com/imduffy15/slack-autoarchive/commit/52ceb23360332d1f124210791f24ebfd45d06429
I have merged https://github.com/alexeiser/slack-autoarchive/pull/3 to address it.

**Comment by alexeiser** [comment]
Oh - and adding the bot tends to add a message which resets your archiving clock....
