### ISSUE TITLE
rate limiting

### ISSUE THREAD

**Issue by JohnTheodore** [Symantec/slack-autoarchive#7]
Slack has recently (in August 2017?) introduced rate limiting. Their API was limited when this script was written, so we queried every channel one at a time to get the history. It might be they added new API functionality to let us batch get history? If you have say 100 channels, it hits a limit. The output looks like this:

➜  slack-autoarchive git:(master) DRY_RUN=False python slack-autoarchive.py
Find inactive channels...
................................Traceback (most recent call last):
  File "slack-autoarchive.py", line 152, in <module>
    inactive_channels       = get_inactive_channels(all_unarchived_channels, TOO_OLD_DATETIME)
  File "slack-autoarchive.py", line 82, in get_inactive_channels
    channel_history = slack_api_http(api_endpoint=api_endpoint, payload=payload)
  File "slack-autoarchive.py", line 37, in slack_api_http
    raise Exception(e)
Exception: {"ok":false,"error":"ratelimited"}

**Comment by altryne** [comment]
Just got this error as well, would love to see some rate-limiting support

**Comment by JohnTheodore** [comment]
@adamkaplan fixed this if you want to checkout the latest version.
